import { colors } from "@/styles/colors"
import { fontFamily } from "@/styles/fontFamily"
import { Platform, StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.primary,
  },
  content: {
    paddingTop: Platform.OS === "android" ? 54 : 64,
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  headerTitle: {
    fontSize: 21,
    fontFamily: fontFamily.semiBold,
    color: colors.primary,
  },
  headerIcon: {
    padding: 4,
  },
  profile: {
    alignItems: "center",
  },
  profileImageWrapper: {
    position: "relative",
    alignSelf: "center",
    marginBottom: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 4,
  },
  profileImage: {
    width: 132,
    height: 132,
    borderRadius: 66,
    borderWidth: 4,
    borderColor: colors.white,
  },
  cameraButton: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  cameraInner: {
    width: 27,
    height: 27,
    borderRadius: 13.5,
    backgroundColor: colors.white,
    alignItems: "center",
    justifyContent: "center",
  },
  profileTitle: {
    fontSize: 27,
    fontFamily: fontFamily.semiBold,
    color: colors.text.primary,
    textAlign: "center",
    marginTop: 20,
  },
  profileSubtitle: {
    fontSize: 15,
    fontFamily: fontFamily.regular,
    color: colors.text.secundary,
    textAlign: "center",
    marginTop: 4,
  },
  semester: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    gap: 8,
    height: 30,
    paddingHorizontal: 14,
    borderRadius: 15,
    backgroundColor: colors.background.blue,
    marginTop: 14,
  },
  semesterText: {
    fontSize: 13,
    fontFamily: fontFamily.semiBold,
    color: colors.text.primary,
  },
  settingsButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    height: 52,
    width: "100%",
    backgroundColor: colors.primary,
    borderRadius: 12,
    marginTop: 28,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  settingsText: {
    fontSize: 16,
    fontFamily: fontFamily.semiBold,
    color: colors.white,
  },
  disciplineCard: {
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    height: 96,
    width: "100%",
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: 20,
    marginTop: 24,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  disciplineDecoration: {
    position: "absolute",
    top: -24,
    right: -24,
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colors.background.blue,
    opacity: 0.6,
  },
  disciplineIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  disciplineInfo: {
    flex: 1,
  },
  cardLabel: {
    fontSize: 12,
    fontFamily: fontFamily.semiBold,
    color: colors.text.secundary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  disciplineTotal: {
    fontSize: 28,
    fontFamily: fontFamily.bold,
    color: colors.text.primary,
    marginTop: 2,
  },
  arrow: {
    marginLeft: 8,
  },
  statsRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 16,
  },
  statCard: {
    position: "relative",
    flex: 1,
    height: 147,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    justifyContent: "space-between",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statDecoration: {
    position: "absolute",
    top: -20,
    right: -20,
    width: 80,
    height: 80,
    borderRadius: 40,
    opacity: 0.5,
  },
  greenDecoration: {
    backgroundColor: "#6BFF8F",
  },
  redDecoration: {
    backgroundColor: colors.background.red,
  },
  statIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  greenIcon: {
    backgroundColor: "#6BFF8F",
  },
  redIcon: {
    backgroundColor: colors.background.red,
  },
  statTotal: {
    fontSize: 28,
    fontFamily: fontFamily.bold,
    marginTop: 8,
  },
  greenTotal: {
    color: colors.text.primary,
  },
  redTotal: {
    color: colors.red,
  },
  statLabel: {
    fontSize: 13,
    fontFamily: fontFamily.medium,
    color: colors.text.secundary,
  },
})
